# Generated by Django 4.0.4 on 2022-04-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('drinks', 'drinks')], max_length=60),
        ),
    ]
